version: '3.8'
services:
  pi8_app:
    container_name: pi8_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx_pi8
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - pi8_app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 
